Secrets and use MariaDBSchema CRD
openstack-k8s-operators/keystone-operator pull request #27
Opened 2020-08-18 22:47 UTC by dprince

Updates the keystone CRD to use secrets.

Additionally, this updates the keystone controller so that it rely's
on the mariadb-operator's MariaDBSchema to create databases for us.

Important to note that the implementation uses the unstructured k8s
client so that we don't explicitly depend on the mariadb-operator code
struct's (and associated golang lib versions).

The old code is removed from the dbsync job and we can also remove
the associated parameters.

2020-08-19 09:19 UTC, mdbooth requested changes
This patch would significantly add to our technical debt. We need to get the MariaDBSchema rename out of the way so we don't continue to proliferate the word 'schema' into more places.

Also, seeing how it's used makes me think we need changes in that object beyond its name.

2020-08-19 09:19 UTC, mdbooth commented on pkg/keystone/volumes.go
> +// common Keystone API VolumeMounts (db-kolla-config mounts passwords directly as keystone-api.conf)
keystone-api.conf is weird keystone-passwords.conf?

2020-08-19 09:19 UTC, mdbooth commented on pkg/keystone/bootstrap.go
> +					InitContainers: []corev1.Container{
It looks like all 3 uses of this init container are identical. This should be common code.

2020-08-19 09:19 UTC, mdbooth commented on templates/mariadb_schema.yaml
> +    dbName: {{.DatabaseHostname}}
I haven't looked hard at MariaDB&lt;Schema&gt; but is this really how we're specifying the database server?

2020-08-26 18:16 UTC, dprince commented on pkg/keystone/bootstrap.go
> +									Name:  "DatabaseHost",
The reason for camelcasing them is solely because that matches the secret entries and thus makes grep'ability greater.

2020-08-26 18:19 UTC, dprince commented
We can agree to disagree but I'm going to go ahead and land this for the secrets and keystone CRD simplifications alone.

I have created a Jira issue where we are tracking the MariaDBSchema name changes (where we'll rename MariaDBSchema to MariaDBDatabase). This will involve changes to mariadb-operator, glance-operator, and keystone-operator.

2020-08-26 18:20 UTC, merged